### ISSUE TITLE
"Trying to get property of non-object" when getting access token with client credentials

### ISSUE THREAD

**Issue by ilCoso** [lucadegasperi/oauth2-server-laravel#347]
Hi Luca,

I'm trying to use oauth with client credentials grant but when I try to obtain the access token i get an error 500 "Trying to get property of non-object"... probably I'm doing something wrong...

This is my call:

![image](https://cloud.githubusercontent.com/assets/1561494/7112806/a8dd23ca-e1cd-11e4-9554-17209cdd7676.png)

...and this is my oauth2.php:

```php
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Database Connection to use
    |--------------------------------------------------------------------------
    |
    | Set the default database connection to use for the repositories,
    | when set to default, it uses whatever connection you specified in your laravel db config.
    |
    */
    'database' => 'oauth',

    /*
    |--------------------------------------------------------------------------
    | Supported Grant Types
    |--------------------------------------------------------------------------
    |
    | Your OAuth2 Server can issue an access token based on different grant types
    | you can even provide your own grant type.
    | To choose which grant type suits your scenario, see
    | https://github.com/php-loep/oauth2-server/wiki/Which-OAuth-2.0-grant-should-I-use%3F
    |
    | Available grant types are:
    |
    | 'grant_types' => [
    |
    |    'authorization_code' => [
    |        'class'            => 'League\OAuth2\Server\Grant\AuthCodeGrant',
    |        'access_token_ttl' => 3600,
    |
    |        // the authorization code time to live
    |        'auth_token_ttl'   => 3600,
    |    ],
    |
    |    'password' => [
    |        'class'            => 'League\OAuth2\Server\Grant\PasswordGrant',
    |        'access_token_ttl' => 604800,
    |
    |        // the code to run in order to verify the user's identity
    |        'callback'         => function($username, $password){
    |            $credentials = [
    |                'email'    => $username,
    |                'password' => $password,
    |            ];
    |
    |            if (Auth::once($credentials)) {
    |                return Auth::user()->id;
    |            } else {
    |                return false;
    |            }
    |        }
    |    ],
    |
    |    'client_credentials' => [
    |        'class'                 => 'League\OAuth2\Server\Grant\ClientCredentialsGrant',
    |        'access_token_ttl'      => 3600,
    |    ],
    |
    |    'refresh_token' => [
    |        'class'                 => 'League\OAuth2\Server\Grant\RefreshTokenGrant',
    |        'access_token_ttl'      => 3600,
    |
    |        // the refresh token time to live
    |        'refresh_token_ttl'     => 604800,
    |
    |        // whether or not to issue a new refresh token when a new access token is issued
    |        'rotate_refresh_tokens' => false,
    |    ],
    |
    | ],
    |
    */

    'grant_types' => [
        'client_credentials' => [
            'class' => '\League\OAuth2\Server\Grant\ClientCredentialsGrant',
            'access_token_ttl' => 3600
        ]
    ],

    /*
    |--------------------------------------------------------------------------
    | Output Token Type
    |--------------------------------------------------------------------------
    |
    | This will tell the authorization server the output format for the access token
    | and will tell the resource server how to parse the access token used.
    |
    | Default value is League\OAuth2\Server\TokenType\Bearer
    |
    */
    'token_type' => 'League\OAuth2\Server\TokenType\Bearer',

    /*
    |--------------------------------------------------------------------------
    | State Parameter
    |--------------------------------------------------------------------------
    |
    | Whether or not the state parameter is required in the query string
    |
    */
    'state_param' => false,

    /*
    |--------------------------------------------------------------------------
    | Scope Parameter
    |--------------------------------------------------------------------------
    |
    | Whether or not the scope parameter is required in the query string
    |
    */
    'scope_param' => false,

    /*
    |--------------------------------------------------------------------------
    | Scope Delimiter
    |--------------------------------------------------------------------------
    |
    | Which character to use to split the scope parameter in the query string
    |
    */
    'scope_delimiter' => ',',

    /*
    |--------------------------------------------------------------------------
    | Default Scope
    |--------------------------------------------------------------------------
    |
    | The default scope to use if not present in the query string
    |
    */
    'default_scope' => null,

    /*
    |--------------------------------------------------------------------------
    | Access Token TTL
    |--------------------------------------------------------------------------
    |
    | For how long the issued access token is valid (in seconds)
    | this can be also set on a per grant-type basis
    |
    */
    'access_token_ttl' => 3600,

    /*
    |--------------------------------------------------------------------------
    | Limit clients to specific grants
    |--------------------------------------------------------------------------
    |
    | Whether or not to limit clients to specific grant types
    | This is useful to allow only trusted clients to access your API differently
    |
    */
    'limit_clients_to_grants' => false,

    /*
    |--------------------------------------------------------------------------
    | Limit clients to specific scopes
    |--------------------------------------------------------------------------
    |
    | Whether or not to limit clients to specific scopes
    | This is useful to only allow specific clients to use some scopes
    |
    */
    'limit_clients_to_scopes' => false,

    /*
    |--------------------------------------------------------------------------
    | Limit scopes to specific grants
    |--------------------------------------------------------------------------
    |
    | Whether or not to limit scopes to specific grants
    | This is useful to allow certain scopes to be used only with certain grant types
    |
    */
    'limit_scopes_to_grants' => false,

    /*
    |--------------------------------------------------------------------------
    | HTTP Header Only
    |--------------------------------------------------------------------------
    |
    | This will tell the resource server where to check for the access_token.
    | By default it checks both the query string and the http headers
    |
    */
    'http_headers_only' => false,
];
```

I also have added a client to the `oauth_clients` table.

Thank you!

**Comment by lucadegasperi** [comment]
have you tried switching to from-data instead of x-www-form-urlencoded ?

**Comment by ilCoso** [comment]
Yes, and I get the same error.

**Comment by lucadegasperi** [comment]
How does the route look like. Can you disable the oauth exception handler middleware to get a better error stack trace?

**Comment by ilCoso** [comment]
The route is:

```php
Route::post('oauth/access_token', function() {
    return Response::json(Authorizer::issueAccessToken());
});
```

And the stack trace is:

```
#0 \vendor\lucadegasperi\oauth2-server-laravel\src\Storage\FluentClient.php(159): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', 159, Array)
#1 \vendor\lucadegasperi\oauth2-server-laravel\src\Storage\FluentClient.php(108): LucaDegasperi\OAuth2Server\Storage\FluentClient->hydrateEntity(Array)
#2 \vendor\league\oauth2-server\src\Grant\ClientCredentialsGrant.php(81): LucaDegasperi\OAuth2Server\Storage\FluentClient->get('1', 'STUBa8esTETrAfR...', NULL, 'client_credenti...')
#3 \vendor\league\oauth2-server\src\AuthorizationServer.php(275): League\OAuth2\Server\Grant\ClientCredentialsGrant->completeFlow()
#4 \vendor\lucadegasperi\oauth2-server-laravel\src\Authorizer.php(80): League\OAuth2\Server\AuthorizationServer->issueAccessToken()
#5 \vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(205): LucaDegasperi\OAuth2Server\Authorizer->issueAccessToken()
#6 \app\routes.php(15): Illuminate\Support\Facades\Facade::__callStatic('issueAccessToke...', Array)
#7 \app\routes.php(15): LucaDegasperi\OAuth2Server\Facades\AuthorizerFacade::issueAccessToken()
#8 [internal function]: {closure}()
#9 \vendor\laravel\framework\src\Illuminate\Routing\Route.php(109): call_user_func_array(Object(Closure), Array)
#10 \vendor\laravel\framework\src\Illuminate\Routing\Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#11 \vendor\laravel\framework\src\Illuminate\Routing\Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#12 \vendor\laravel\framework\src\Illuminate\Foundation\Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#13 \vendor\laravel\framework\src\Illuminate\Foundation\Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#14 \vendor\barryvdh\laravel-debugbar\src\Middleware\Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#15 \vendor\asm89\stack-cors\src\Asm89\Stack\Cors.php(51): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#16 \vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Asm89\Stack\Cors->handle(Object(Illuminate\Http\Request), 1, true)
#17 \vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#18 \vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#19 \vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#20 \vendor\laravel\framework\src\Illuminate\Foundation\Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#21 \public\index.php(49): Illuminate\Foundation\Application->run()
#22 {main}
```

**Comment by lucadegasperi** [comment]
have you set PDO to return arrays instead of objects or vice-versa? Looks like the issue originates from the FluentClient.

**Comment by ilCoso** [comment]
Perfect! I have switched from `FETCH_CLASS` to `FETCH_ASSOC` because I need it in my project, but if I switch back in runtime everyting works fine. (I don't know if it is a good practice but it works)

```php
Route::post('oauth/access_token', function() {
	Config::set('database.fetch', PDO::FETCH_CLASS);
    return Response::json(Authorizer::issueAccessToken());
});
```

Thank you!
