### ISSUE TITLE
explode() expects parameter 2 to be string, object given

### ISSUE THREAD

**Issue by choiks14** [lucadegasperi/oauth2-server-laravel#450]
http://localhost/oauth/authorize?response_type=code&client_id=c5a87df6-cef8-4395-bfff-7babb29a6138

i use auth code. but 
explode() expects parameter 2 to be string, object given

**Comment by lucadegasperi** [comment]
Please paste an error log, otherwise I can't help you with only this description.

**Comment by beznez** [comment]
I am having the same error. This is my curl command.

```curl
curl "http://domain.com/oauth/access_token" -d "grant_type=password" -d "client_id=client1id" -d "client_secret=client1secret" -d "username=user" -d "password=password"
```

Here is the route for the request.

```php
Route::post('/oauth/access_token', function()
{
    return Resonse::json(Authorizer::issueAccessToken());
});
```

And here is the stack trace.

````
[2015-07-02 15:52:12] local.ERROR: exception 'ErrorException' with message 'explode() expects parameter 2 to be string, object given' in /var/www/html/universal_menudrive_api/vendor/lucadegasperi/oauth2-server-laravel/src/OAuth2ServerServiceProvider.php:101
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'explode() expec...', '/var/www/html/u...', 101, Array)
#1 /var/www/html/universal_menudrive_api/vendor/lucadegasperi/oauth2-server-laravel/src/OAuth2ServerServiceProvider.php(101): explode('@', Object(Closure))
#2 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Container/Container.php(274): LucaDegasperi\OAuth2Server\OAuth2ServerServiceProvider->LucaDegasperi\OAuth2Server\{closure}(Object(Illuminate\Foundation\Application))
#3 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Container/Container.php(733): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array)
#4 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Container/Container.php(626): Illuminate\Container\Container->build(Object(Closure), Array)
#5 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('oauth2-server.a...', Array)
#6 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Container/Container.php(1157): Illuminate\Foundation\Application->make('oauth2-server.a...')
#7 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(149): Illuminate\Container\Container->offsetGet('oauth2-server.a...')
#8 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(118): Illuminate\Support\Facades\Facade::resolveFacadeInstance('oauth2-server.a...')
#9 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(203): Illuminate\Support\Facades\Facade::getFacadeRoot()
#10 /var/www/html/universal_menudrive_api/app/Http/routes.php(40): Illuminate\Support\Facades\Facade::__callStatic('issueAccessToke...', Array)
#11 /var/www/html/universal_menudrive_api/app/Http/routes.php(40): LucaDegasperi\OAuth2Server\Facades\Authorizer::issueAccessToken()
#12 [internal function]: Uma\Providers\RouteServiceProvider->{closure}()
#13 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(155): call_user_func_array(Object(Closure), Array)
#14 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(130): Illuminate\Routing\Route->runCallable(Object(Illuminate\Http\Request))
#15 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(704): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(706): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#21 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(671): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#22 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(631): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#23 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(229): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#24 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 /var/www/html/universal_menudrive_api/vendor/lucadegasperi/oauth2-server-laravel/src/Middleware/OAuthExceptionHandlerMiddleware.php(18): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 [internal function]: LucaDegasperi\OAuth2Server\Middleware\OAuthExceptionHandlerMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#29 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(54): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#32 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#35 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#38 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#41 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#44 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#46 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#47 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(86): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#48 /var/www/html/universal_menudrive_api/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#49 {main} 
````

**Comment by beznez** [comment]
I re-implemented my grant type in `config/oauth2.php`. I removed the function that was there and defined it in a class as per the [password grant guide](https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Implementing-an-Authorization-Server-with-the-Password-Grant). After I moved it to a class and redefined the callback as `'\YourAppNamespace\Verifier@verify'`, I ran the curl command again and I received my access token. So it looks like you have to give callback a string, not a function. That is what explode is complaining about.

**Comment by vinkla** [comment]
@beznez solution should work find if that is your issue. Otherwise this issue hasn't been updated in a while and I'll close this for now. @choiks14 get back to us if you're still having problems with this.

**Comment by SoldierCorp** [comment]
I can't solve my issue, I have the same problem.

I have this info in oauth2.php

    'callback' => function($username, $password) {
                if (Auth::validate([
                    'email'    => $username,
                    'password' => $password,
                ])) {
                    $user = \App\User::where('email',$username)->first();
                    return $user->id;
                } else {
                    return false;
                }
            },

So as the solution that @beznez provided Is better to use 

    'callback' => '\YourAppNamespace\Verifier@verify',

But I've created a controller with that verify function putting the same block of code I have in oauth2.php but is not working.

**Comment by lucadegasperi** [comment]
It definitively should work that way.

**Comment by SoldierCorp** [comment]
But is not working using the function or even using the Verifier because the is showing 

    Class \App\Verifier not found

I'm using the Password grant by the way.
