### ISSUE TITLE
How to add a new custom grant type?

### ISSUE THREAD

**Issue by beznez** [lucadegasperi/oauth2-server-laravel#463]
I want to add a new custom grant type. This grant type should be called `guest` and it is needed so I can keep track of a guest cart without a user being required to register and login. I added this to `config/oauth2.php`:

```php
'guest' => [
            'class' => '\League\OAuth2\Server\Grant\PasswordGrant',
            'callback' => '\App\Verifier@guest',
            'access_token_ttl' => 3600
        ],
```

And in `Verifier` I added my `guest` method:

```php
public function guest($guest_token, $password = null)
    {
        \Log::info('guest grant has fired!');
        return true;
    }
```

Then I used curl to get an access token:

```curl
curl "http://domain.com/oauth/accessToken" -d "grant_type=guest"
```

And I receive this error:

```sh
[2015-07-14 15:36:52] local.ERROR: exception 'League\OAuth2\Server\Exception\UnsupportedGrantTypeException' with message 'The authorization grant type "guest" is not supported by the authorization server.' in /var/www/html/universal_menudrive_api/vendor/league/oauth2-server/src/AuthorizationServer.php:271
Stack trace:
#0 /var/www/html/universal_menudrive_api/vendor/lucadegasperi/oauth2-server-laravel/src/Authorizer.php(80): League\OAuth2\Server\AuthorizationServer->issueAccessToken()
#1 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(207): LucaDegasperi\OAuth2Server\Authorizer->issueAccessToken()
#2 /var/www/html/universal_menudrive_api/app/Http/routes.php(39): Illuminate\Support\Facades\Facade::__callStatic('issueAccessToke...', Array)
#3 /var/www/html/universal_menudrive_api/app/Http/routes.php(39): LucaDegasperi\OAuth2Server\Facades\Authorizer::issueAccessToken()
#4 [internal function]: Uma\Providers\RouteServiceProvider->{closure}()
#5 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(155): call_user_func_array(Object(Closure), Array)
#6 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(130): Illuminate\Routing\Route->runCallable(Object(Illuminate\Http\Request))
#7 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(704): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(706): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(671): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#14 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(631): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#15 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(229): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(54): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#21 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#24 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#27 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#30 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#33 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#36 /var/www/html/universal_menudrive_api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(86): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#37 /var/www/html/universal_menudrive_api/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#38 {main}
```

Did I miss a step?

**Comment by vinkla** [comment]
Did you add the new `guest` grant to the database as well?

**Comment by beznez** [comment]
No, so just add an entry to `oauth_grants`? Any other tables that need information seeded?

**Comment by vinkla** [comment]
No that should be enough. Why do you want a guest grant in the first place? Doesn't that loose the entire purpose of using an OAuth2 server?

**Comment by beznez** [comment]
It was for an API call to get a 'guest' token as opposed to a 'user' token to manage a cart. We've decided on another way to do this that will not use this strategy. However, I left this issue open because I wanted to know in case I ever have to add a custom grant type or if someone else could use help with this same thing. Thanks!
