### ISSUE TITLE
Laravel 5.1 DB Connection problem

### ISSUE THREAD

**Issue by ngugijames** [lucadegasperi/oauth2-server-laravel#529]
I'm on laravel 5.1,  "5.0.*@dev" version of this package. 
Uisng Laragon 0.8 on windows 8.
My .env file is as follows
DB_HOST=localhost
DB_DATABASE=accounts_manager
DB_USERNAME=dean
DB_PASSWORD=dean
The oauth2 service is being consumed using oauth2client. For the AuthCodeGrant Type, the code is issued successfully, however, request for the access token fails. 
Inspect of the oauth2 app logs reveals the following:
[2015-08-19 07:07:44] local.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user 'homestead'@'localhost' (using password: YES)' in ...laravel\framework\src\Illuminate\Database\Connectors\Connector.php:50
Stack trace:
#0 ...laravel\framework\src\Illuminate\Database\Connectors\Connector.php(50): PDO->__construct('mysql:host=loca...', 'homestead', 'secret', Array)
#1 ...laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(22): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#2 ...laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php(60): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 ...laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php(49): Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection(Array)
#4 ...laravel\framework\src\Illuminate\Database\DatabaseManager.php(175): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'oauth_mysql')
#5 ...laravel\framework\src\Illuminate\Database\DatabaseManager.php(67): Illuminate\Database\DatabaseManager->makeConnection('oauth_mysql')
#6 ...lucadegasperi\oauth2-server-laravel\src\Storage\AbstractFluentAdapter.php(88): Illuminate\Database\DatabaseManager->connection('oauth_mysql')
#7 ...lucadegasperi\oauth2-server-laravel\src\Storage\FluentClient.php(96): LucaDegasperi\OAuth2Server\Storage\AbstractFluentAdapter->getConnection()
#8 ...league\oauth2-server\src\Grant\ClientCredentialsGrant.php(81): LucaDegasperi\OAuth2Server\Storage\FluentClient->get('o5pmWZdPwbKgRlQ...', 'eyJpdiI6IjV4eWh...', NULL, 'client_credenti...')
#9 ...league\oauth2-server\src\AuthorizationServer.php(276): League\OAuth2\Server\Grant\ClientCredentialsGrant->completeFlow()
#10 ...lucadegasperi\oauth2-server-laravel\src\Authorizer.php(96): League\OAuth2\Server\AuthorizationServer->issueAccessToken()
#11 ...laravel\framework\src\Illuminate\Support\Facades\Facade.php(207): LucaDegasperi\OAuth2Server\Authorizer->issueAccessToken()
#12 C:\laragon\www\AccountsManager\app\Http\routes.php(58): Illuminate\Support\Facades\Facade::__callStatic('issueAccessToke...', Array)
#13 C:\laragon\www\AccountsManager\app\Http\routes.php(58): LucaDegasperi\OAuth2Server\Facades\Authorizer::issueAccessToken()
#14 [internal function]: AccountsManager\Providers\RouteServiceProvider->{closure}()
....truncated

My db is set to accounts_manager in .env but the package tries to connect to a db called homestead, using password secret. I'm i missing something, is there a configuration i forgot to specify?

**Comment by vinkla** [comment]
Your issue is very messy and I can't really make anything of it. Could you please try to explain a bit more and add more information.

**Comment by vinkla** [comment]
Closing due to inactivity.

**Comment by skokhuis** [comment]
I had the same issue. I think it's related to the Fluent connection in combination with Laravel (5.2 in my case). It seems either the SQL is eval'd or the active db connection is mixed when a token is issued. This only happens when I have two laravel installations (one oAuth server and one client) on the same server. When I run the server and client script on seperate servers it works fine.

The queries executed in /vendor/lucadegasperi/oauth2-server-laravel/src/Storage/FluentClient.php at line 81 use the database connection from the oAuth client, while the code lives on the oAuth server.

Hope this helps someone.

**Comment by reyrahadian** [comment]
@skokhuis I have the same problem as well

Is there a workaround for this? using a separate servers for Oauth Server and Oauth Client for my scenario is not feasible as the two is in one server for development purpose

**Comment by skokhuis** [comment]
@reyrahadian For my use case seperate servers / app containers was workable. Unfortunately I have no solution or explanation for this behaviour.
